### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ghost** [lightswitch05/commit-cloud#1]
No matter what repository I choose, I always get a 404 error.

In addition, It might also be desirable to use SSL links. GitHub pages supports it out of the box.

**Comment by lightswitch05** [comment]
After some research, the Github API has changed since I originally developed this tool. Since then, the [library I was using has been deprecated](https://github.com/philschatz/octokat.js), so its going to be a little more work then expected to get this working again. I'll probably eventually get around to it, but I'm very busy at work. Pull requests are welcome!

**Comment by lightswitch05** [comment]
This appears to have magically started working again
